<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <UserSecretsId>booking-worker-portfolio</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Booking.Contracts\Booking.Contracts.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.1"/>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.2"/>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.11"/>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1"/>
  </ItemGroup>

</Project>
