#Requires -Version 7.0
#Requires -Modules Az.Accounts, Az.Resources, Az.Websites

<#
.SYNOPSIS
    Deploys the booking platform infrastructure and the API code.

.DESCRIPTION
    Runs infra/main.bicep at subscription scope, then publishes the .NET API to the
    App Service it created, then locks that App Service down to API Management's
    outbound addresses.

    The lockdown is a separate step for a reason that is not obvious from the
    template: APIM needs the App Service hostname to configure its backend, so the
    app must exist before APIM does, which means the app cannot know APIM's
    outbound IPs at deployment time. It is a genuine ordering constraint, not an
    oversight.

    The backend key is generated here and never written to disk. It goes into Key
    Vault via a secure template parameter; APIM reads it as a named value and the
    App Service reads it as a Key Vault reference. No copy exists anywhere else.

.PARAMETER ParameterFile
    Bicep parameters file. Copy infra/main.parameters.example.json and edit it.

.PARAMETER SubscriptionId
    Target subscription. Defaults to the current context.

.PARAMETER SkipCodeDeploy
    Provision infrastructure only.

.PARAMETER SkipIpRestriction
    Leave the App Service open to the internet. Useful while debugging, dangerous
    to forget - the script prints a warning when it is used.

.PARAMETER WhatIf
    Preview the infrastructure changes without applying them.

.EXAMPLE
    ./Deploy-Infrastructure.ps1 -ParameterFile ../infra/main.parameters.json

.EXAMPLE
    ./Deploy-Infrastructure.ps1 -ParameterFile ../infra/main.parameters.json -WhatIf
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string] $ParameterFile,

    [string] $SubscriptionId,

    [switch] $SkipCodeDeploy,

    [switch] $SkipIpRestriction
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$templateFile = Join-Path $repoRoot 'infra/main.bicep'
$apiProject = Join-Path $repoRoot 'src/Booking.Api/Booking.Api.csproj'

function Write-Step {
    param([string] $Message)
    Write-Host ''
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function New-BackendKey {
    <#
        32 bytes from a cryptographic RNG, base64 encoded, returned as a
        SecureString that was never a plain String.

        Not New-Guid: a GUID is 122 bits of which several are structural, and it
        is not generated by a CSPRNG.

        Not the -AsPlainText conversion either: that requires the secret to exist
        as an immutable managed String first, which then lingers in memory until
        it is collected and cannot be cleared. Encoding straight into a char
        array avoids ever creating one, and PSScriptAnalyzer flags the
        alternative as an error for exactly this reason.
    #>
    $bytes = [byte[]]::new(32)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)

    $chars = [char[]]::new([int][Math]::Ceiling($bytes.Length / 3.0) * 4)
    $written = [Convert]::ToBase64CharArray($bytes, 0, $bytes.Length, $chars, 0)

    $secure = [System.Security.SecureString]::new()
    for ($index = 0; $index -lt $written; $index++) {
        $secure.AppendChar($chars[$index])
    }
    $secure.MakeReadOnly()

    [Array]::Clear($chars, 0, $chars.Length)
    [Array]::Clear($bytes, 0, $bytes.Length)

    return $secure
}

# --- Preconditions ---------------------------------------------------------

Write-Step 'Checking prerequisites'

if (-not (Test-Path $templateFile)) {
    throw "Template not found at $templateFile. Run this script from the repository."
}

$context = Get-AzContext
if (-not $context) {
    throw 'Not signed in. Run Connect-AzAccount first.'
}

if ($SubscriptionId) {
    Write-Host "Selecting subscription $SubscriptionId"
    $context = Set-AzContext -Subscription $SubscriptionId
}

Write-Host "Subscription : $($context.Subscription.Name) ($($context.Subscription.Id))"
Write-Host "Account      : $($context.Account.Id)"
Write-Host "Parameters   : $ParameterFile"

$parameters = Get-Content $ParameterFile -Raw | ConvertFrom-Json
$location = $parameters.parameters.location.value
if (-not $location) { throw "The parameters file must set 'location'." }

if ($parameters.parameters.apimPublisherEmail.value -like '*REPLACE_ME*') {
    throw "apimPublisherEmail is still the placeholder. Edit $ParameterFile before deploying."
}

# --- Infrastructure --------------------------------------------------------

Write-Step 'Deploying infrastructure'

$backendKey = New-BackendKey
$deploymentName = "booking-platform-$(Get-Date -Format 'yyyyMMdd-HHmmss')"

$deploymentArgs = @{
    Name                    = $deploymentName
    Location                = $location
    TemplateFile            = $templateFile
    TemplateParameterFile   = $ParameterFile
    backendKey              = $backendKey
    ErrorAction             = 'Stop'
}

if ($WhatIfPreference) {
    Write-Host 'Running what-if; nothing will be changed.' -ForegroundColor Yellow
    New-AzSubscriptionDeployment @deploymentArgs -WhatIf
    return
}

$deployment = New-AzSubscriptionDeployment @deploymentArgs

if ($deployment.ProvisioningState -ne 'Succeeded') {
    throw "Deployment finished with state $($deployment.ProvisioningState)."
}

$outputs = $deployment.Outputs
$resourceGroupName = $outputs.resourceGroupName.Value
$apiAppName        = $outputs.apiAppName.Value
$apiUrl            = $outputs.apiUrl.Value
$apimName          = $outputs.apimName.Value
$apimGatewayUrl    = $outputs.apimGatewayUrl.Value

Write-Host ''
Write-Host 'Deployed:' -ForegroundColor Green
Write-Host "  Resource group : $resourceGroupName"
Write-Host "  API            : $apiUrl"
Write-Host "  Gateway        : $apimGatewayUrl"
Write-Host "  Service Bus    : $($outputs.serviceBusNamespace.Value)"
Write-Host "  Key Vault      : $($outputs.keyVaultName.Value)"
Write-Host "  Worker identity: $($outputs.workerIdentityClientId.Value)"

# --- Application code ------------------------------------------------------

if (-not $SkipCodeDeploy) {
    Write-Step 'Publishing the API'

    $publishDir = Join-Path ([System.IO.Path]::GetTempPath()) "booking-api-$([Guid]::NewGuid().ToString('N'))"
    $zipPath = "$publishDir.zip"

    try {
        & dotnet publish $apiProject -c Release -o $publishDir --nologo
        if ($LASTEXITCODE -ne 0) { throw "dotnet publish failed with exit code $LASTEXITCODE." }

        Compress-Archive -Path (Join-Path $publishDir '*') -DestinationPath $zipPath -Force

        if ($PSCmdlet.ShouldProcess($apiAppName, 'Publish application package')) {
            Publish-AzWebApp -ResourceGroupName $resourceGroupName `
                             -Name $apiAppName `
                             -ArchivePath $zipPath `
                             -Force | Out-Null
            Write-Host "Published to $apiAppName" -ForegroundColor Green
        }
    }
    finally {
        Remove-Item $publishDir -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item $zipPath -Force -ErrorAction SilentlyContinue
    }

    Write-Step 'Waiting for the API to report healthy'
    $healthy = $false
    foreach ($attempt in 1..30) {
        try {
            $response = Invoke-WebRequest -Uri "$apiUrl/health" -TimeoutSec 10 -SkipHttpErrorCheck
            if ($response.StatusCode -eq 200) { $healthy = $true; break }
        }
        catch {
            # Cold start on a Linux App Service routinely takes 30-60 seconds.
            Write-Verbose "Attempt $attempt : $($_.Exception.Message)"
        }
        Start-Sleep -Seconds 5
    }

    if ($healthy) {
        Write-Host 'API is healthy.' -ForegroundColor Green
    }
    else {
        Write-Warning "The API did not report healthy within 150 seconds. Check the log stream: az webapp log tail -g $resourceGroupName -n $apiAppName"
    }
}

# --- Lock the origin down --------------------------------------------------

if ($SkipIpRestriction) {
    Write-Warning 'IP restriction skipped. The App Service is reachable directly, so every gateway policy can be bypassed. Do not leave it this way.'
}
else {
    Write-Step 'Restricting the App Service to API Management'

    $apim = Get-AzResource -ResourceGroupName $resourceGroupName `
                           -ResourceType 'Microsoft.ApiManagement/service' `
                           -Name $apimName `
                           -ExpandProperties

    # Consumption tier reports a set of shared outbound addresses; other tiers
    # report one public IP. Both live in publicIPAddresses/outboundPublicIPAddresses.
    $outboundIps = @()
    foreach ($property in 'outboundPublicIPAddresses', 'publicIPAddresses') {
        if ($apim.Properties.PSObject.Properties.Name -contains $property) {
            $value = $apim.Properties.$property
            if ($value) { $outboundIps += @($value) }
        }
    }
    $outboundIps = $outboundIps | Where-Object { $_ } | Select-Object -Unique

    if (-not $outboundIps) {
        Write-Warning 'Could not determine the API Management outbound addresses; skipping the IP restriction. The X-Backend-Key check in the app is still in force.'
    }
    elseif ($PSCmdlet.ShouldProcess($apiAppName, "Allow only $($outboundIps -join ', ')")) {
        $priority = 100
        foreach ($ip in $outboundIps) {
            Add-AzWebAppAccessRestrictionRule -ResourceGroupName $resourceGroupName `
                                              -WebAppName $apiAppName `
                                              -Name "apim-$priority" `
                                              -Priority $priority `
                                              -Action Allow `
                                              -IpAddress "$ip/32" `
                                              -ErrorAction SilentlyContinue | Out-Null
            $priority += 10
        }

        # An explicit final Deny. Without it App Service falls back to
        # "allow everything not otherwise matched" only when no Allow rule exists;
        # with Allow rules present the implicit deny applies, but stating it makes
        # the intent readable in the portal.
        Add-AzWebAppAccessRestrictionRule -ResourceGroupName $resourceGroupName `
                                          -WebAppName $apiAppName `
                                          -Name 'deny-all' `
                                          -Priority 2147483647 `
                                          -Action Deny `
                                          -IpAddress '0.0.0.0/0' `
                                          -ErrorAction SilentlyContinue | Out-Null

        Write-Host "Restricted $apiAppName to $($outboundIps.Count) API Management address(es)." -ForegroundColor Green
    }
}

# --- Next steps ------------------------------------------------------------

Write-Step 'Next'

Write-Host @"
1. Import the API and apply the policies:
     ./Import-ApimApi.ps1 -ResourceGroupName $resourceGroupName -ApimName $apimName

2. Register the Entra ID application (docs/entra-id-setup.md), then redeploy with
   entraTenantId and entraApiApplicationId set so validate-jwt has an issuer.

3. Smoke test through the gateway:
     ./Invoke-SmokeTests.ps1 -GatewayUrl $apimGatewayUrl -SubscriptionKey <key>

Deployment name: $deploymentName
"@
